'''
programacion orientada a objetos, es un paradigma de la programacion. Paradigma: un conjunto de problemas y soluciones modelos que son de 
interes a cierta area del conocimiento, en este caso hacia la programacion. 
se considera que a todo se puede modelar como un objeto, dentro de los programas estos objetos seran colecciones de datos o atributos y 
comportamientos que tendran esos objetos 

#clase: va a proveer de la estructura de la cual podemos crear un onbjeto

existe la programacion basada en objetos y la programciohn orientada a objetos
la diferencia entre estos dos es que en la programacion orientada a objetos hay algo que se llama herencia 
lo que hace la herencia es tratar de simular mejor la realidad, tratar de crear clases especificas para cierto tipo
por ejemplo tengo clases de personas, un artista es una persona y un deportista es otra, ambos son una persona pero cada uno tiene 
caracteristicas distintas y lo que se puede hacer con la herencia es que uno tome las mismas caracteristicas del otro pero agregandole algunas
caracteristicas mas que el anterior
o tomo como base una persona y creo otra con respecto a esa pero con mas caracteristicas
dsp tenemos el polimorfismo, esto se refiere a que ambas personas tengan una misma caracteristica pero que cada uno ejecute su caracteristica de
forma distinta
ejemplo dos personajes de un juego, ambos atacan pero cada uno ataca de una forma distinta
'''
